// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA56diDh0DP7M8ylp0Z67ZsSBC5Vo4d6ZM',
    appId: '1:842682753637:web:6e2505a29de043af639c8c',
    messagingSenderId: '842682753637',
    projectId: 'project-flutter1-99e01',
    authDomain: 'project-flutter1-99e01.firebaseapp.com',
    storageBucket: 'project-flutter1-99e01.firebasestorage.app',
    measurementId: 'G-DJT6XQY5JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzpzv5IqcslD_p-G9kDFvz-o8dC07LkuU',
    appId: '1:842682753637:android:65d8a20f228fe36c639c8c',
    messagingSenderId: '842682753637',
    projectId: 'project-flutter1-99e01',
    storageBucket: 'project-flutter1-99e01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE2cyv0MPRcOR1GFdkrdGhqH4SVpVPf8Q',
    appId: '1:842682753637:ios:55b6b8f8cbbe7ba8639c8c',
    messagingSenderId: '842682753637',
    projectId: 'project-flutter1-99e01',
    storageBucket: 'project-flutter1-99e01.firebasestorage.app',
    iosBundleId: 'com.example.projectFlutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE2cyv0MPRcOR1GFdkrdGhqH4SVpVPf8Q',
    appId: '1:842682753637:ios:55b6b8f8cbbe7ba8639c8c',
    messagingSenderId: '842682753637',
    projectId: 'project-flutter1-99e01',
    storageBucket: 'project-flutter1-99e01.firebasestorage.app',
    iosBundleId: 'com.example.projectFlutter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA56diDh0DP7M8ylp0Z67ZsSBC5Vo4d6ZM',
    appId: '1:842682753637:web:77fc07716c9100bb639c8c',
    messagingSenderId: '842682753637',
    projectId: 'project-flutter1-99e01',
    authDomain: 'project-flutter1-99e01.firebaseapp.com',
    storageBucket: 'project-flutter1-99e01.firebasestorage.app',
    measurementId: 'G-HSJECQ58RR',
  );
}
